stages:
  - build
  - test

build-job:
    stage: build
    image: node:lts
    tags: 
        - docker-np
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - ./node_modules
            - ./build

test-job:
  stage: test
  tags:
      - docker-np
  script:
      - echo "test successful"