stages:
  - build
  - test
  - deploy

build-job:
    stage: build
    image: node:lts
    tags: 
        - docker-np
    script:
        - npm install
        - npm run build
        - mv ./build ./public
    artifacts:
        paths:
            - ./public

test-job:
  stage: test
  tags:
      - docker-np
  script:
      - echo "test successful"

deploy_staging:
  stage: deploy
  tags:
    - docker-np
  before_script:
        - apt-get update -qq
        - apt-get install -qq git
        - 'which ssh-agent || ( apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh fusion@158.160.102.242 "sudo chown -R fusion:fusion /home/fusion/project_np"
    - ssh fusion@158.160.102.242 "cd /home/fusion/project_np && git pull origin && JhRembo && fGu8vBFL@314 && exit"
  only:
    - main