stages:
  - build
  - test

build-job:
    stage: build
    image: node:lts
    tags: 
        - docker-np
    script:
        - npm install
        - npm run build
    artifacts:
        paths:
            - ./build

test-job:
  stage: test
  tags:
      - docker-np
  script:
      - echo "test successful"

deploy_staging:
  stage: deploy
  before_script:
        - apt-get update -qq
        - apt-get install -qq git
  # Setup SSH deploy keys
        - 'which ssh-agent || ( apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh fusion@158.160.102.242 "cd var/www/ && git checkout master && git pull origin master && exit"
  only:
    - main