deploy:
  image: alpine
  tags:
      - frontendruner
  before_script:
    - apk add openssh-client
    - apk add git
    - apk add npm
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - scp -r 
    - mkdir gitdir
    - cd gitdir
    - git clone git@gitlab.com:JhRembo/frontend.git
    - git checkout dev
    - git pull

  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_PIPELINE_SOURCE == "push"
      
  
      
    