name: test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: setup key
      with: 
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
    - run: ssh -T ubuntu@54.215.213.58
    - run: pwd
