name: test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install openssh-client
      - run:  eval $(ssh-agent -s)
      - run: echo "${{secrets.SSH_PRIVATE_KEY}}"
      - run: ssh-add ${{secrets.SSH_PRIVATE_KEY}}
      - run: mkdir -p ~/.ssh
      - run: chmod 700 ~/.ssh
